service: serverless
frameworkVersion: '3.19.0'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-south-1
  stage: prod


functions:
  getInfo:
    handler: handler.getInfo
    events:
     - http:
        path: users/info
        method: get

  createInfo:
    handler: handlerpost.createInfo
    events:
     - http:
        path: users/create
        method: post

  patchInfo:
    handler: handlerpatch.patchInfo
    events:
     - http:
        path: users/update
        method: patch