service: usersCrud
provider: aws
resources:
  Resources:
    usersTable:
      Type: 'AWS::DynamoDB::Table'
      Properties: null
      TableName: usersTable
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
